### ISSUE TITLE
Broken android project gradle builds after updating android gradle plugin to 4.1.0

### ISSUE THREAD

**Issue by mdocevski-infinum** [novoda/gradle-android-command-plugin#152] opened 2020-11-10 12:08 UTC
After updating the Android Gradle plugin to 4.1.0 and gradle to 6.5 (or newer), I'm unable to build any project that uses the command plugin. I'm getting the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
> Extension not initialized yet, couldn't access compileSdkVersion.
```

Full stack trace, with debug and info flags: [command.log](https://github.com/novoda/gradle-android-command-plugin/files/5517094/command.log)

Gradle scan: https://scans.gradle.com/s/jowammjf5ku2y

It's not a project specific problem, I've added the command plugin to an empty project, and have the same issue.

**Comment by tasomaniac** [comment] 2020-11-10 18:23
I know they did behavior changes in 4.1 about how they call the extensions. Unless they're designed to be lazy, Android Gradle plugin will be more eager to configure.

We are probably resolving this too early. Although I think this plug-in has ben upgraded to Lazy APIs and should not call this eagerly.

The fix is probably is as easy as putting an afterEvaluate where we access this. Any contributions would be welcome.

**Comment by arberg** [comment] 2021-05-18 09:25
I can confirm that moving moving the apply plugin into afterEvaluate lets me use the plugin just as before, without any further changes. It also works with kotlin build-scripts. 

As felipehjcosta's commit demonstrates above:
```
afterEvaluate {
        apply(plugin = "com.novoda.android-command")
}
```

So this seems to be a fine work-around for now.

**Closed as completed** 2022-02-11 01:58 UTC
